openshift_adm_migrate_template_instances -  new module
openshift/community.okd pull request #126
Opened 2021-11-10 12:22 UTC by alinabuzachis

`openshift_adm_migrate_template_instances` -  new module to update TemplateInstances to point to the latest group-version-kinds.

2021-11-11 09:01 UTC, Akasurde requested changes
minor fixes. Rest LGTM

2021-11-11 09:44 UTC, alinabuzachis commented on plugins/modules/openshift_adm_migrate_template_instances.py
> +# along with Ansible.  If not, see <http://www.gnu.org/licenses/>.
@Akasurde Thank you. Done!

2021-11-17 10:27 UTC, abikouo approved these changes
Good Job @alinabuzachis !!!

2021-11-17 10:27 UTC, abikouo commented on plugins/modules/openshift_adm_migrate_template_instances.py
> +    openshift_process.argspec = argument_spec
I dont really see where this is used

2021-11-17 11:28 UTC, merged